sudo: required
services:
  - docker

before_install:
  - docker build -t facundoalarcon/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true facundoalarcon/react-test npm test

after_success:
  - docker build -t facundoalarcon/xdsawmwa-client ./client
  - docker build -t facundoalarcon/xdsawmwa-nginx ./nginx
  - docker build -t facundoalarcon/xdsawmwa-server ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them docker hub
  - docker push facundoalarcon/xdsawmwa-client
  - docker push facundoalarcon/xdsawmwa-nginx
  - docker push facundoalarcon/xdsawmwa-server
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-ml'
  env: 'DockerMl-env'
  bucket_name: 'elasticbeanstalk-us-east-1-863537803557'
  bucket_path: 'docker-ml'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY